name: firstprojectflutter #Название пакета приложения 
description: "My First Flutter application" #Описания приложения для Package
publish_to: 'none' #Перечисления сайтов, куда будет опубликован данные приложения или сайта
version: 1.0.0+1  #Версия приложения

environment: #Устанавливает какую версию языка Dart использует Flutter проект
  sdk: ^3.11.0-17.0.dev

dependencies: #Зависимость приложения
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 #Стандартные куплетеновские наборы иконок для IOS приложений (можно использовать также для Android)
  flutter_svg: ^2.2.1
  dio: ^5.9.0
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  talker_flutter: ^5.0.2
  talker_dio_logger: ^5.0.2
  
  
    
dev_dependencies: #Зависимость приложения Flutter в момент разработки
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0 #Не пойдет в итоговую сборку приложения (не будет занимать лишнее место у пользователей на их устройствах)


flutter: #Все дополнительные зависимости Flutter приложения и конфигурационные настройки
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
