// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKd6NDXPJBlvNoLWFflF-nk4nzDItfoPw',
    appId: '1:328666907245:web:a3b53b7c3de7d5ad65b564',
    messagingSenderId: '328666907245',
    projectId: 'crypto-list-app-flutter',
    authDomain: 'crypto-list-app-flutter.firebaseapp.com',
    storageBucket: 'crypto-list-app-flutter.firebasestorage.app',
    measurementId: 'G-G5ELYHF49C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmK_cmpeR0O7XonutAaiRaxDWVBYEyIzU',
    appId: '1:328666907245:android:216615a297d31cfb65b564',
    messagingSenderId: '328666907245',
    projectId: 'crypto-list-app-flutter',
    storageBucket: 'crypto-list-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIKblfWBdbIHU_QpkmB8sDnkJB7XFEeJQ',
    appId: '1:328666907245:ios:2c0684ab0849e6ab65b564',
    messagingSenderId: '328666907245',
    projectId: 'crypto-list-app-flutter',
    storageBucket: 'crypto-list-app-flutter.firebasestorage.app',
    iosBundleId: 'com.helloworld.firstprojectflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIKblfWBdbIHU_QpkmB8sDnkJB7XFEeJQ',
    appId: '1:328666907245:ios:2c0684ab0849e6ab65b564',
    messagingSenderId: '328666907245',
    projectId: 'crypto-list-app-flutter',
    storageBucket: 'crypto-list-app-flutter.firebasestorage.app',
    iosBundleId: 'com.helloworld.firstprojectflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKd6NDXPJBlvNoLWFflF-nk4nzDItfoPw',
    appId: '1:328666907245:web:59bd8c47bf52c60e65b564',
    messagingSenderId: '328666907245',
    projectId: 'crypto-list-app-flutter',
    authDomain: 'crypto-list-app-flutter.firebaseapp.com',
    storageBucket: 'crypto-list-app-flutter.firebasestorage.app',
    measurementId: 'G-CQQ6ZR7X9T',
  );
}
